name: geofence_service
description: This plugin is a geofence service with activity recognition API.
version: 4.0.0
publish_to: none
homepage: https://github.com/Dev-hwang/geofence_service

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

  fl_location: ^2.1.0
  flutter_activity_recognition: 
    git: https://github.com/prossion/flutter_activity_recognition.git
  flutter_foreground_task: ^4.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.pravera.geofence_service
        pluginClass: GeofenceServicePlugin
      ios:
        pluginClass: GeofenceServicePlugin
